import jsPDF from "jspdf";
import "jspdf-autotable";
import { format } from "date-fns";
import type { KKKSRecord } from "@/data/mockData";
import {
  initializePDF,
  addHeader,
  addFooter,
  addWatermark,
  addSectionTitle,
  addParagraph,
  addKeyValue,
  checkPageBreak,
  formatNumber,
  formatPercentage,
  PDF_CONFIG,
  getContentArea,
} from "./pdfGenerator";

export interface ReportData {
  title: string;
  period: string;
  generatedBy: string;
  summary: {
    totalWK: number;
    certified: number;
    pilot: number;
    onboarding: number;
    registration: number;
    avgCompliance: number;
    implementationProgress: number;
  };
  kkksData: KKKSRecord[];
  charts?: {
    statusDistribution?: string; // Base64 image
    complianceRanking?: string;
    sigiDomainCoverage?: string;
    implementationTrend?: string;
  };
}

/**
 * Generate comprehensive PDF report
 */
export const generatePDFReport = async (data: ReportData): Promise<jsPDF> => {
  const doc = initializePDF();
  const generatedDate = new Date();
  let currentY = PDF_CONFIG.margins.top;

  // Add watermark to first page
  addWatermark(doc);

  // Add header
  addHeader(doc, data.title, generatedDate);
  currentY = PDF_CONFIG.margins.top;

  // ===== COVER PAGE =====
  currentY = addCoverPage(doc, data, currentY);

  // Add new page for content
  doc.addPage();
  addWatermark(doc);
  currentY = PDF_CONFIG.margins.top;

  // ===== EXECUTIVE SUMMARY =====
  currentY = addExecutiveSummary(doc, data, currentY);

  // ===== IMPLEMENTATION STATUS =====
  currentY = checkPageBreak(doc, currentY, 80);
  currentY = addImplementationStatus(doc, data, currentY);

  // ===== COMPLIANCE ANALYSIS =====
  currentY = checkPageBreak(doc, currentY, 80);
  currentY = addComplianceAnalysis(doc, data, currentY);

  // ===== CHARTS SECTION =====
  if (data.charts) {
    doc.addPage();
    addWatermark(doc);
    currentY = PDF_CONFIG.margins.top;
    currentY = addChartsSection(doc, data, currentY);
  }

  // ===== DETAILED KKKS TABLE =====
  doc.addPage();
  addWatermark(doc);
  currentY = PDF_CONFIG.margins.top;
  currentY = addDetailedKKKSTable(doc, data, currentY);

  // ===== RECOMMENDATIONS =====
  doc.addPage();
  addWatermark(doc);
  currentY = PDF_CONFIG.margins.top;
  currentY = addRecommendations(doc, data, currentY);

  // Add footers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages, generatedDate);
  }

  return doc;
};

/**
 * Add cover page
 */
const addCoverPage = (doc: jsPDF, data: ReportData, startY: number): number => {
  let y = startY + 50;

  // Title
  doc.setFontSize(24);
  doc.setFont(PDF_CONFIG.fonts.display, "bold");
  doc.setTextColor(...PDF_CONFIG.colors.primary);
  const titleLines = doc.splitTextToSize(data.title, 150);
  doc.text(titleLines, PDF_CONFIG.page.width / 2, y, { align: "center" });
  y += titleLines.length * 12;

  // Subtitle
  y += 10;
  doc.setFontSize(14);
  doc.setFont(PDF_CONFIG.fonts.body, "normal");
  doc.setTextColor(...PDF_CONFIG.colors.secondary);
  doc.text("SPEKTRUM IOG 4.0 Monitoring System", PDF_CONFIG.page.width / 2, y, {
    align: "center",
  });
  y += 30;

  // Report details box
  const boxWidth = 120;
  const boxHeight = 60;
  const boxX = (PDF_CONFIG.page.width - boxWidth) / 2;
  const boxY = y;

  doc.setDrawColor(...PDF_CONFIG.colors.border);
  doc.setFillColor(250, 250, 250);
  doc.rect(boxX, boxY, boxWidth, boxHeight, "FD");

  y = boxY + 15;
  doc.setFontSize(10);
  doc.setTextColor(...PDF_CONFIG.colors.secondary);

  // Period
  doc.setFont(PDF_CONFIG.fonts.body, "bold");
  doc.text("Reporting Period:", boxX + 10, y);
  doc.setFont(PDF_CONFIG.fonts.body, "normal");
  doc.text(data.period, boxX + 50, y);
  y += 10;

  // Generated date
  doc.setFont(PDF_CONFIG.fonts.body, "bold");
  doc.text("Generated Date:", boxX + 10, y);
  doc.setFont(PDF_CONFIG.fonts.body, "normal");
  doc.text(format(new Date(), "dd MMMM yyyy"), boxX + 50, y);
  y += 10;

  // Generated by
  doc.setFont(PDF_CONFIG.fonts.body, "bold");
  doc.text("Generated By:", boxX + 10, y);
  doc.setFont(PDF_CONFIG.fonts.body, "normal");
  doc.text(data.generatedBy, boxX + 50, y);
  y += 10;

  // Classification
  doc.setFont(PDF_CONFIG.fonts.body, "bold");
  doc.text("Classification:", boxX + 10, y);
  doc.setFont(PDF_CONFIG.fonts.body, "normal");
  doc.setTextColor(...PDF_CONFIG.colors.destructive);
  doc.text("CONFIDENTIAL", boxX + 50, y);

  return y + 50;
};

/**
 * Add executive summary section
 */
const addExecutiveSummary = (doc: jsPDF, data: ReportData, startY: number): number => {
  let y = addSectionTitle(doc, "Executive Summary", startY);

  const summary = data.summary;

  // Key metrics in a grid
  const metrics = [
    { label: "Total WK Monitored", value: formatNumber(summary.totalWK) },
    { label: "Certified Connections", value: formatNumber(summary.certified) },
    { label: "Pilot Phase", value: formatNumber(summary.pilot) },
    { label: "Onboarding", value: formatNumber(summary.onboarding) },
    { label: "Registration", value: formatNumber(summary.registration) },
    {
      label: "Average Compliance",
      value: formatPercentage(summary.avgCompliance),
    },
    {
      label: "Implementation Progress",
      value: formatPercentage(summary.implementationProgress),
    },
  ];

  const contentArea = getContentArea();
  const boxWidth = (contentArea.width - 10) / 2;
  const boxHeight = 18;
  const spacing = 5;

  let row = 0;
  let col = 0;

  metrics.forEach((metric, index) => {
    const x = PDF_CONFIG.margins.left + col * (boxWidth + spacing);
    const boxY = y + row * (boxHeight + spacing);

    // Draw box
    doc.setDrawColor(...PDF_CONFIG.colors.border);
    doc.setFillColor(248, 249, 250);
    doc.rect(x, boxY, boxWidth, boxHeight, "FD");

    // Label
    doc.setFontSize(9);
    doc.setFont(PDF_CONFIG.fonts.body, "normal");
    doc.setTextColor(...PDF_CONFIG.colors.muted);
    doc.text(metric.label, x + 5, boxY + 7);

    // Value
    doc.setFontSize(14);
    doc.setFont(PDF_CONFIG.fonts.display, "bold");
    doc.setTextColor(...PDF_CONFIG.colors.primary);
    doc.text(metric.value, x + 5, boxY + 14);

    col++;
    if (col >= 2) {
      col = 0;
      row++;
    }
  });

  y += Math.ceil(metrics.length / 2) * (boxHeight + spacing) + 10;

  return y;
};

/**
 * Add implementation status section
 */
const addImplementationStatus = (
  doc: jsPDF,
  data: ReportData,
  startY: number
): number => {
  let y = addSectionTitle(doc, "Implementation Status", startY);

  const { summary } = data;
  const total = summary.totalWK;

  // Status breakdown text
  const text = `Out of ${total} Wilayah Kerja (WK) being monitored, ${summary.certified} have achieved CERTIFIED status (${formatPercentage((summary.certified / total) * 100)}), ${summary.pilot} are in PILOT phase (${formatPercentage((summary.pilot / total) * 100)}), ${summary.onboarding} are ONBOARDING (${formatPercentage((summary.onboarding / total) * 100)}), and ${summary.registration} are in REGISTRATION phase (${formatPercentage((summary.registration / total) * 100)}).`;

  y = addParagraph(doc, text, y);
  y += 5;

  // Progress towards target
  const targetText = `The overall implementation progress stands at ${formatPercentage(summary.implementationProgress)}, representing ${summary.certified + summary.pilot} WK that are actively connected to the SPEKTRUM IOG 4.0 platform.`;
  y = addParagraph(doc, targetText, y);

  return y + 5;
};

/**
 * Add compliance analysis section
 */
const addComplianceAnalysis = (
  doc: jsPDF,
  data: ReportData,
  startY: number
): number => {
  let y = addSectionTitle(doc, "SIGI Compliance Analysis", startY);

  const text = `The average SIGI compliance score across all monitored WK is ${formatPercentage(data.summary.avgCompliance)}. This metric reflects the degree to which connected KKKS entities are adhering to the PPDM data standards and SIGI domain coverage requirements.`;

  y = addParagraph(doc, text, y);
  y += 5;

  // Top performers
  const topPerformers = [...data.kkksData]
    .sort((a, b) => b.sigiComplianceScore - a.sigiComplianceScore)
    .slice(0, 5);

  y = addParagraph(doc, "Top 5 Performing WK by Compliance Score:", y);
  y += 3;

  topPerformers.forEach((kkks, index) => {
    doc.setFontSize(9);
    doc.setFont(PDF_CONFIG.fonts.body, "normal");
    doc.setTextColor(...PDF_CONFIG.colors.secondary);
    doc.text(
      `${index + 1}. ${kkks.wilayahKerja} - ${formatPercentage(kkks.sigiComplianceScore)}`,
      PDF_CONFIG.margins.left + 5,
      y
    );
    y += 5;
  });

  return y + 5;
};

/**
 * Add charts section
 */
const addChartsSection = (doc: jsPDF, data: ReportData, startY: number): number => {
  let y = addSectionTitle(doc, "Visual Analytics", startY);

  const contentArea = getContentArea();
  const imageWidth = contentArea.width / 2 - 5;
  const imageHeight = 70;

  // Add charts in 2x2 grid
  const charts = [
    { key: "statusDistribution", title: "Connection Status Distribution" },
    { key: "complianceRanking", title: "Top 15 WK by Compliance" },
    { key: "sigiDomainCoverage", title: "SIGI Domain Coverage" },
    { key: "implementationTrend", title: "Implementation Progress Trend" },
  ];

  let row = 0;
  let col = 0;

  for (const chart of charts) {
    const imageData = data.charts?.[chart.key as keyof typeof data.charts];

    if (imageData) {
      const x = PDF_CONFIG.margins.left + col * (imageWidth + 10);
      const chartY = y + row * (imageHeight + 20);

      // Chart title
      doc.setFontSize(10);
      doc.setFont(PDF_CONFIG.fonts.body, "bold");
      doc.setTextColor(...PDF_CONFIG.colors.secondary);
      doc.text(chart.title, x, chartY);

      // Add image
      try {
        doc.addImage(imageData, "PNG", x, chartY + 5, imageWidth, imageHeight);
      } catch (error) {
        console.error(`Failed to add chart ${chart.key}:`, error);
      }

      col++;
      if (col >= 2) {
        col = 0;
        row++;
      }
    }
  }

  return y + Math.ceil(charts.length / 2) * (imageHeight + 20) + 10;
};

/**
 * Add detailed KKKS table
 */
const addDetailedKKKSTable = (
  doc: jsPDF,
  data: ReportData,
  startY: number
): number => {
  let y = addSectionTitle(doc, "Detailed KKKS Status", startY);

  const tableData = data.kkksData.map((kkks) => [
    kkks.wilayahKerja,
    kkks.kkksName,
    kkks.connectionStatus,
    formatPercentage(kkks.sigiComplianceScore),
    `${kkks.ppdmModulesActivated}/${kkks.ppdmModulesTotal}`,
    format(new Date(kkks.lastSync), "dd MMM yyyy"),
  ]);

  doc.autoTable({
    startY: y,
    head: [["WK", "KKKS", "Status", "Compliance", "PPDM Modules", "Last Sync"]],
    body: tableData,
    theme: "grid",
    headStyles: {
      fillColor: PDF_CONFIG.colors.primary,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: PDF_CONFIG.colors.secondary,
    },
    alternateRowStyles: {
      fillColor: [248, 249, 250],
    },
    margin: { left: PDF_CONFIG.margins.left, right: PDF_CONFIG.margins.right },
    didDrawPage: (data) => {
      // Add watermark to each new page
      if (data.pageNumber > 1) {
        addWatermark(doc);
      }
    },
  });

  // @ts-ignore - autoTable adds finalY property
  return doc.lastAutoTable.finalY + 10;
};

/**
 * Add recommendations section
 */
const addRecommendations = (
  doc: jsPDF,
  data: ReportData,
  startY: number
): number => {
  let y = addSectionTitle(doc, "Recommendations", startY);

  const recommendations = [
    {
      title: "Priority Focus Areas",
      text: `Focus on advancing the ${data.summary.onboarding} WK currently in ONBOARDING status to PILOT phase through targeted technical assistance and training programs.`,
    },
    {
      title: "Compliance Improvement",
      text: `Implement compliance enhancement initiatives for WK with scores below 70% to meet the minimum acceptable threshold. Consider establishing peer mentoring programs between high and low-performing entities.`,
    },
    {
      title: "Module Activation",
      text: "Accelerate PPDM module activation across all WK, with emphasis on critical domains such as Well (210), Production (230), and Seismic (220) data.",
    },
    {
      title: "Certificate Management",
      text: "Establish proactive certificate renewal processes to prevent service disruptions for CERTIFIED connections approaching expiry dates.",
    },
  ];

  recommendations.forEach((rec, index) => {
    y = checkPageBreak(doc, y, 30);

    doc.setFontSize(11);
    doc.setFont(PDF_CONFIG.fonts.body, "bold");
    doc.setTextColor(...PDF_CONFIG.colors.primary);
    doc.text(`${index + 1}. ${rec.title}`, PDF_CONFIG.margins.left, y);
    y += 7;

    y = addParagraph(doc, rec.text, y);
    y += 5;
  });

  return y;
};
